services:
  app:
    build:
      context: ./src
    container_name: devops-e2-semana7-app
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      PORT: 3000
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: devops
      DB_PASSWORD: devops123
      DB_NAME: devopse2
    ports:
      - "8080:3000"
    restart: unless-stopped

  mysql:
    image: mysql:8.4
    container_name: devops-e2-semana7-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: devopse2
      MYSQL_USER: devops
      MYSQL_PASSWORD: devops123
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u$$MYSQL_USER -p$$MYSQL_PASSWORD"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 15s
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql_data:
